general {
    lock_cmd = pidof hyprlock || hyprlock       # what to run when told to lock
    before_sleep_cmd = loginctl lock-session    # extra safety if you ever manually suspend
}

# 2 Minutes: Lock the screen
listener {
    timeout = 180           
    on-timeout = loginctl lock-session           
}

# 2.5 Minutes: Turn off the display (DPMS)
listener {
    timeout = 210                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         # turn screen back on when you move the mouse
}
